#version: '3.3'
services:
  web:
    build:
      context: ./
    command: node -r global-agent/bootstrap src/index.js
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    environment:
      NODE_ENV: production
      DEBUG: nodejs-docker-express:*
      HTTP_PROXY: http://10.1.6.20:80
      HTTPS_PROXY: http://10.1.6.20:80
      NO_PROXY: localhost,127.0.0.1
      GLOBAL_AGENT_HTTP_PROXY: http://10.1.6.20:80